import 'dart:convert';

import 'package:bip39/bip39.dart' as bip39;
import 'package:cryptography/cryptography.dart';

import 'package:homl/data/models/settings.dart';
import 'package:homl/helpers/event_search.dart';
import 'package:homl/helpers/local_storage_manager.dart';

/// Client side of the opt-in end-to-end encryption (homl-web/docs/e2ee.md).
///
/// A 16-byte seed lives in the device secure storage (and nowhere else —
/// exportable only as a 12-word recovery phrase). Two working keys are
/// derived from it with HKDF: a content key for AES-256-GCM value encryption
/// and an index key for the tag blind indexes and the key check. When
/// [enabled], the repositories encrypt on write and decrypt on read, so the
/// rest of the app only ever sees plaintext.
class E2ee {
  static final E2ee _instance = E2ee._internal();
  factory E2ee() => _instance;
  E2ee._internal();

  /// Marks a client-encrypted value: base64(nonce || ciphertext || mac).
  static const prefix = 'e2ee:v1:';

  static const _contentInfo = 'homl-e2ee:v1:content';
  static const _indexInfo = 'homl-e2ee:v1:index';
  static const _keyCheckMessage = 'homl-e2ee:v1:keycheck';

  /// Fixed HKDF salt. A salt is optional for HKDF, but the native Android
  /// HMAC (via cryptography_flutter) rejects the empty key that an absent
  /// salt produces in HKDF-Extract ("IllegalArgumentException: Empty key").
  /// A constant app salt keeps the derivation deterministic and portable.
  static const _hkdfSalt = 'homl-e2ee:v1:salt';

  static const _nonceLength = 12;
  static const _macLength = 16;

  /// The backend creates its date tags with English month names; the client
  /// mirrors that under E2EE so an enable/disable round trip is stable. The
  /// same list doubles as the tag blacklist (masterdata BLACKLIST_TAGS),
  /// enforced client-side because the server cannot read E2EE tag names.
  static const englishMonths = [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ];

  final _aes = AesGcm.with256bits();
  final _hmac = Hmac.sha256();

  bool _enabled = false;
  SecretKey? _contentKey;
  SecretKey? _indexKey;

  /// Seed generated by [prepareEnable] but not yet persisted: it only reaches
  /// the secure storage once the migration succeeded ([commitEnable]).
  List<int>? _pendingSeed;

  /// Whether the repositories must encrypt/decrypt. True only when the server
  /// flag is set AND the key is loaded.
  bool get enabled => _enabled && _contentKey != null;

  Future<void> _deriveKeys(List<int> seed) async {
    final hkdf = Hkdf(hmac: Hmac.sha256(), outputLength: 32);
    final salt = utf8.encode(_hkdfSalt);
    _contentKey = await hkdf.deriveKey(
        secretKey: SecretKey(seed),
        nonce: salt,
        info: utf8.encode(_contentInfo));
    _indexKey = await hkdf.deriveKey(
        secretKey: SecretKey(seed),
        nonce: salt,
        info: utf8.encode(_indexInfo));
  }

  /// Resolves the E2EE state after authentication. Returns false when the
  /// account is end-to-end encrypted but this device holds no (matching) key:
  /// the caller must block the app on the restore-or-purge screen. A stored
  /// key that fails the key check is kept in storage (it may belong to
  /// another account using this device) but is not used.
  Future<bool> unlock(Settings? settings) async {
    final storedSeed = await _readStoredSeed();

    if (settings == null) {
      // Settings unreachable (offline start): trust the stored key when there
      // is one so the cached data stays readable.
      if (storedSeed != null) {
        await _deriveKeys(storedSeed);
        _enabled = true;
      }
      return true;
    }

    if (!settings.isE2eeEnabled) {
      lock();
      return true;
    }

    if (storedSeed == null) return false;

    await _deriveKeys(storedSeed);
    if (settings.e2eeKeyCheck != null &&
        settings.e2eeKeyCheck != await keyCheck()) {
      lock();
      return false;
    }

    _enabled = true;
    return true;
  }

  /// Generates a fresh seed and returns its recovery phrase. The seed is kept
  /// in memory only until [commitEnable]; [abortEnable] discards it.
  Future<String> prepareEnable() async {
    final mnemonic = bip39.generateMnemonic(strength: 128);
    final seed = _seedFromMnemonic(mnemonic);
    _pendingSeed = seed;
    await _deriveKeys(seed);
    return mnemonic;
  }

  /// Persists the pending seed once the enable migration succeeded.
  Future<void> commitEnable() async {
    final seed = _pendingSeed;
    if (seed == null) throw StateError('No pending E2EE seed to commit');
    await LocalStorageManager.setValue(
        LocalStorageKey.e2eeMasterKey, base64.encode(seed));
    _pendingSeed = null;
    _enabled = true;
  }

  /// Discards a pending enable attempt (user cancelled or migration failed).
  void abortEnable() {
    _pendingSeed = null;
    lock();
  }

  /// Wipes the stored key after a successful disable migration.
  Future<void> disable() async {
    await LocalStorageManager.remove(LocalStorageKey.e2eeMasterKey);
    lock();
  }

  /// Restores the key from a typed recovery phrase, verified against the
  /// server-stored key check before anything is persisted.
  Future<bool> restore(String mnemonic, String? expectedKeyCheck) async {
    final normalized = mnemonic.trim().toLowerCase().split(RegExp(r'\s+')).join(' ');
    if (!bip39.validateMnemonic(normalized)) return false;

    final seed = _seedFromMnemonic(normalized);
    await _deriveKeys(seed);
    if (expectedKeyCheck != null && expectedKeyCheck != await keyCheck()) {
      lock();
      return false;
    }

    await LocalStorageManager.setValue(
        LocalStorageKey.e2eeMasterKey, base64.encode(seed));
    _enabled = true;
    return true;
  }

  /// Clears the in-memory keys (logout / lock). The stored seed is untouched:
  /// the same user unlocks again on the next login.
  void lock() {
    _enabled = false;
    _contentKey = null;
    _indexKey = null;
  }

  /// Encrypts a value with a random nonce: `e2ee:v1:` + base64(nonce||ct||mac).
  Future<String> encrypt(String plaintext) async {
    final box = await _aes.encrypt(utf8.encode(plaintext),
        secretKey: _requireKey(_contentKey));
    return prefix + base64.encode(box.concatenation());
  }

  /// Decrypts an `e2ee:v1:` value. Anything else is returned verbatim, so a
  /// mixed payload (legacy plaintext) cannot crash the read path.
  Future<String> decrypt(String value) async {
    if (!value.startsWith(prefix)) return value;

    final raw = base64.decode(value.substring(prefix.length));
    final box = SecretBox.fromConcatenation(raw,
        nonceLength: _nonceLength, macLength: _macLength);
    final clear = await _aes.decrypt(box, secretKey: _requireKey(_contentKey));
    return utf8.decode(clear);
  }

  /// Blind index of a tag name: first 16 bytes of HMAC-SHA256 over the
  /// normalized name, lowercase hex. Deterministic, so the server can enforce
  /// uniqueness and search by equality without learning the name.
  Future<String> tagIndex(String tagName) async {
    final mac = await _hmac.calculateMac(
        utf8.encode(normalizeTagName(tagName)),
        secretKey: _requireKey(_indexKey));
    return _hex(mac.bytes.sublist(0, 16));
  }

  /// Full HMAC-SHA256 of a fixed string, stored server-side at enable so a
  /// restoring device can verify a typed phrase even with no data to decrypt.
  Future<String> keyCheck() async {
    final mac = await _hmac.calculateMac(utf8.encode(_keyCheckMessage),
        secretKey: _requireKey(_indexKey));
    return _hex(mac.bytes);
  }

  /// Whether creating [tagName] is forbidden (mirror of the backend
  /// masterdata blacklist, which the server skips for E2EE users).
  bool isBlacklistedTag(String tagName) =>
      englishMonths.contains(normalizeTagName(tagName));

  Future<List<int>?> _readStoredSeed() async {
    final stored =
        await LocalStorageManager.getValue(LocalStorageKey.e2eeMasterKey);
    if (stored == null) return null;
    try {
      return base64.decode(stored);
    } on FormatException {
      return null;
    }
  }

  /// The 16-byte seed IS the BIP39 entropy: 12 words encode it exactly.
  List<int> _seedFromMnemonic(String mnemonic) =>
      _bytesFromHex(bip39.mnemonicToEntropy(mnemonic));

  SecretKey _requireKey(SecretKey? key) {
    if (key == null) throw StateError('E2EE key is not loaded');
    return key;
  }

  static String _hex(List<int> bytes) =>
      bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

  static List<int> _bytesFromHex(String hex) => [
        for (var i = 0; i < hex.length; i += 2)
          int.parse(hex.substring(i, i + 2), radix: 16)
      ];
}
